=== sapoi/MetaRMS/SharedLibrary/Files/jsonschema.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "http://sapoi.aspifyhost.com/jsonschema.json",
    "title": "MetaRMS application descriptor schema",
    "description": "A JSON schema of a string describing one application for MetaRMS application.",

    "definitions": {
        "attribute": {
            "type": "object",
            "properties": {
                "Name": {
                    "type": "string"
                },
                "Description": {
                    "type": ["string", "null"]
                },
                "Type": {
                    "type": "string"
                },
                "OnDeleteAction": {
                    "type": "string",
                    "enum": ["cascade", "setEmpty", "protect"]
                },
                "Required": {
                    "type": ["boolean", "null"]
                },
                "Unique": {
                    "type": ["boolean", "null"]
                },
                "Safer": {
                    "type": ["boolean", "null"]
                },
                "Min": {
                    "type": ["integer", "null"]
                },
                "Max": {
                    "type": ["integer", "null"]
                }
            },
            "required": ["Name", "Type"],
            "additionalProperties": false
        }
    },

    "type": "object",
    "properties": {
        "ApplicationName": {
            "type": "string"
        },
        "LoginApplicationName": {
            "type": "string"
        },
        "DefaultLanguage": {
            "type": "string",
            "enum": ["en"]
        },
        "SystemDatasets": {
            "type": "object",
            "properties": {
                "UsersDatasetDescriptor": {
                    "type": "object",
                    "properties": {
                        "Name": {
                            "type": "string",
                            "not": {
                                "enum": ["color", "date", "datetime", "email", "month", "int", "float", "year", "phone", "string", "time", "url", "username", "password", "bool", "text"],
                                "pattern": "{[0-1]+}"
                            }
                        },
                        "Description": {
                            "type": ["string", "null"]
                        },
                        "PasswordAttribute": {
                            "$ref": "#/definitions/attribute"
                        },
                        "Attributes": {
                            "type": "array",
                            "minItems": 1,
                            "uniqueItems": true,
                            "items": {
                                "$ref": "#/definitions/attribute"
                            }
                        }
                    },
                    "required": ["Name", "PasswordAttribute", "Attributes"],
                    "additionalProperties": false
                }
            },
            "required": ["UsersDatasetDescriptor"],
            "additionalProperties": false
        },
        "Datasets": {
            "type": "array",
            "minItems": 1,
            "uniqueItems": true,
            "items": {
                "type": "object",
                "properties": {
                    "Name": {
                        "type": "string",
                        "not": {
                            "enum": ["color", "date", "datetime", "email", "month", "int", "float", "year", "phone", "string", "time", "url", "username", "password", "bool", "text"],
                            "pattern": ".*{[0-1]+}.*"
                        }
                    },
                    "Description": {
                        "type": ["string", "null"]
                    },
                    "Attributes": {
                        "type": "array",
                        "minItems": 1,
                        "uniqueItems": true,
                        "items": {
                            "$ref": "#/definitions/attribute"
                        }
                    }
                },
                "required": ["Name", "Attributes"],
                "additionalProperties": false
            }
        }
    },
    "required": ["ApplicationName", "LoginApplicationName", "DefaultLanguage", "SystemDatasets", "Datasets"],
    "additionalProperties": false
}

=== sapoi/MetaRMS/SharedLibrary/jsonappdescriptor.json
{
   "ApplicationName":"all references test",
   "LoginApplicationName":"all_ref_test2",
   "DefaultLanguage":"en",
   "SystemDatasets":{
      "UsersDatasetDescriptor":{
         "Name":"Uživatelé",
         "Description":"Dataset s uživateli aplikace.",
         "PasswordAttribute":{
            "Name":"Password",
            "Description":null,
            "Type":"password",
            "Required":true,
            "Unique":null,
            "Safer":null,
            "Min":null,
            "Max":null
         },
         "Attributes":[
            {
               "Name":"Pozice",
               "Description":null,
               "Type":"username",
               "Required":true,
               "Unique":true,
               "Safer":null,
               "Min":null,
               "Max":null
            },
            {
               "Name":"Pozice2",
               "Type":"string"
            },
            {
               "Name":"Uživatel",
               "Type":"text",
               "Min":10
            },
            {
               "Name":"Uživatel2",
               "Type":"Uživatelé",
               "Required": true,
               "OnDeleteAction":"protect"
            }
         ]
      }
   },
   "Datasets":[
      {
         "Name":"342341}string",
         "Description":null,
         "Attributes":[
            {
               "Name":"Název pozice",
               "Type":"text",
               "Required": true
            }
         ]
      },
      {
         "Name":"url2",
         "Description":null,
         "Attributes":[
            {
               "Name":"Jméno měsíce",
               "Description":null,
               "Type":"text",
               "Required":true,
               "Unique":null,
               "Safer":null,
               "Min":null,
               "Max":null
            }
         ]
      },
      {
         "Name":"A-{35x}A",
         "Description":null,
         "Attributes":[
            {
               "Name":"Jméno měsíce",
               "Description":null,
               "Type":"Uživatelé",
               "Required":true,
               "Unique":null,
               "Safer":null,
               "Min":null,
               "Max":2,
               "OnDeleteAction":"protect"
            }
         ]
      },
      {
         "Name":"url3",
         "Description":null,
         "Attributes":[
            {
               "Name":"Měsíc",
               "Description":null,
               "Type":"Uživatelé",
               "Required":true,
               "Unique":null,
               "Safer":null,
               "Max":9,
               "OnDeleteAction":"setEmpty"
            },
            {
               "Name":"Uživatelé",
               "Description":null,
               "Type":"Uživatelé",
               "Required":true,
               "Unique":null,
               "Safer":null,
               "Min":1,
               "Max":null,
               "OnDeleteAction":"setEmpty"
            },
            {
               "Name":"url",
               "Description":null,
               "Type":"Uživatelé",
               "Required":null,
               "Unique":null,
               "Safer":null,
               "Min":7,
               "Max":null,
               "OnDeleteAction":"setEmpty"
            }
         ]
      }
   ]
}

=== sapoi/MetaRMS/SharedLibrary/Files/ApplicationDescriptorExamples/test_application_descriptor2.json
{
   "ApplicationName":"test2",
   "LoginApplicationName":"test2",
   "DefaultLanguage":"en",
   "SystemDatasets":{
      "UsersDatasetDescriptor":{
         "Name":"Users{12}",
         "Description":"Dataset s uÅ¾ivateli aplikace.",
         "PasswordAttribute":{
            "Name":"Password",
            "Type":"password",
            "Required":true,
            "Min":-1,
            "Max":-1
         },
         "Attributes":[
            {
               "Name":"Usernam{23}e",
               "Type":"username",
               "Required":true,
               "Unique":true,
               "Min":-1,
               "Max":-1
            }
         ]
      }
   },
   "Datasets":[
      {
         "Name":"no min max valid",
         "Description":null,
         "Attributes":[
            {
               "Name":"Color",
               "Type":"color"
            },
            {
               "Name":"Date",
               "Type":"date"
            },
            {
               "Name":"Datetime",
               "Type":"datetime"
            },
            {
               "Name":"Email",
               "Type":"email",
               "Required":true
            },
            {
               "Name":"Month",
               "Type":"month"
            },
            {
               "Name":"Phone",
               "Type":"phone"
            },
            {
               "Name":"Time",
               "Type":"time"
            },
            {
               "Name":"Url",
               "Type":"url"
            },
            {
               "Name":"Bool",
               "Type":"bool"
            }
         ]
      },
      {
         "Name":"min max > 0 jen pro",
         "Attributes":[
            {
               "Name":"Text",
               "Type":"text",
               "Min":-1,
               "Max":-1,
               "Required":true
            },
            {
               "Name":"String",
               "Type":"string",
               "Min":-1,
               "Max":-1
            },
            {
               "Name":"Ref",
               "Type":"Users",
               "Min":-1,
               "Max":-1
            },
            {
               "Name":"Int",
               "Type":"int",
               "Min":-1,
               "Max":-1
            },
            {
               "Name":"Float",
               "Type":"float",
               "Min":-1,
               "Max":-1
            },
            {
               "Name":"Year",
               "Type":"year",
               "Min":-1,
               "Max":-1
            }
         ]
      }
   ]
}

=== sapoi/MetaRMS/SharedLibrary/Files/ApplicationDescriptorExamples/package_delivery_cz.json
{
    "ApplicationName": "Systém pro řízení firmy na přepravu zásilek",
    "LoginApplicationName": "package_delivery",
    "DefaultLanguage": "en",
    "SystemDatasets": {
        "UsersDatasetDescriptor": {
            "Name": "Zaměstnanci",
            "Description": "V tomto datasetu jsou zaměstnanci zásilkové služby.",
            "PasswordAttribute": {
                "Name": "Heslo",
                "Description": "Heslo zaměstnance. Toto heslo musí obsahovat alespoň jedno malé a jedno velké písmeno a jednu číslici nebo speciální znak. Dékla hesla musí být mezi 8 a 15 znaky.",
                "Type": "password",
                "Required": true,
                "Safer": true,
                "Min": 8,
                "Max": 15
            },
            "Attributes": [
                {
                    "Name": "Uživatelské jméno",
                    "Description": "Toho jméno používá uživatel při přihlašování do svého účtu",
                    "Type": "username",
                    "Required": true,
                    "Unique": true
                },
                {
                    "Name": "Jméno",
                    "Description": "Celé jméno zaměstnance",
                    "Type": "string",
                    "Required": true
                },
                {
                    "Name": "Pozice",
                    "Description": "Pozice zaměstnance v rámci firmy",
                    "Type": "Pozice",
                    "OnDeleteAction": "protect",
                    "Required": true
                },
                {
                    "Name": "Nadřízený",
                    "Description": "Nadřízený zaměstnance. Tato osoba je zodpovědná z převzetí práce zaměstnance a za kontrolu splnění veškerých zodpovědností.",
                    "Type": "Zaměstnanci",
                    "Max": 1,
                    "OnDeleteAction": "protect",
                    "Required": false
                },
                {
                    "Name": "Pobočka",
                    "Description": "Pobočka, pro kterou zaměstnanec pracuje",
                    "Type": "Pobočky",
                    "OnDeleteAction": "protect",
                    "Required": false
                }
            ]
        }
    },
    "Datasets": [
        {
            "Name": "Zásilky",
            "Description": "V tomto datasetu se vyskytují všchny zásilky bez ohledu na jejich stav.",
            "Attributes": [
                {
                    "Name": "Identifikátor zásilky",
                    "Description": "Identifikátor zásilky je číslo napsané na boku krabice se zásilkou.",
                    "Type": "string",
                    "Required": true
                },
                {
                    "Name": "Zákazník",
                    "Description": "Zákazník, který posílá zásilku",
                    "Type": "Zákazníci",
                    "Required": true,
                    "Min": 1,
                    "Max": 1,
                    "OnDeleteAction": "cascade"
                },
                {
                    "Name": "Status",
                    "Description": "Status zásilky z výčtu statusů v datasetu Statusy.",
                    "Type": "Statusy",
                    "Required": true,
                    "Min": 1,
                    "Max": 1,
                    "OnDeleteAction": "protect"
                },
                {
                    "Name": "Adresa adresáta",
                    "Description": "Adresa, na kterou se má zásilka poslat",
                    "Type": "text"
                },
                {
                    "Name": "Adresa odesílatele",
                    "Description": "Adresa, na kterou se má zásilka poslat v případě nenalezení adresáta",
                    "Type": "text"
                },
                {
                    "Name": "Datum odeslání zásilky",
                    "Description": "Datum, kdy byla zásilka odeslána",
                    "Type": "datetime",
                    "Required": true
                },
                {
                    "Name": "Zodpovědná osoba",
                    "Description": "Zaměstnanec, který má zásilku na starosti",
                    "Type": "Zaměstnanci",
                    "Min": 1,
                    "Max": 1,
                    "OnDeleteAction": "protect"
                },
                {
                    "Name": "Současná poloha",
                    "Description": "Současná poloha zásilky",
                    "Type": "string",
                    "Required": true
                },
                {
                    "Name": "Cena zásilky",
                    "Description": "Cena za celou zásilku",
                    "Type": "float",
                    "Required": true
                },
                {
                    "Name": "Měna ceny zásilky",
                    "Type": "Měny",
                    "OnDeleteAction": "protect",
                    "Required": true
                },
                {
                    "Name": "Ukončená zásilka",
                    "Description": "Je již zásilka ukončená?",
                    "Type": "bool",
                    "Required": true
                }
            ]
        },
        {
            "Name": "Zákazníci",
            "Description": "Tento dataset obsahuje zákazníky zásilkové společnosti.",
            "Attributes": [
                {
                    "Name": "Jméno",
                    "Description": "Jméno zákazníka",
                    "Type": "string",
                    "Required": true
                },
                {
                    "Name": "Adresa",
                    "Description": "Adresa zákazníka pro doručení zásilek",
                    "Type": "text",
                    "Required": true
                }
            ]
        },
        {
            "Name": "Pobočky",
            "Description": "Tento dataset obsahuje pobočky zásilkové firmy.",
            "Attributes": [
                {
                    "Name": "Název",
                    "Description": "Název pobočky",
                    "Type": "string",
                    "Required": true
                },
                {
                    "Name": "Adresa",
                    "Description": "Adresa pobočky",
                    "Type": "text",
                    "Required": true
                }
            ]
        },
        {
            "Name": "Statusy",
            "Description": "Tento dataset obsahuje jednotlivé statusy zásilek.",
            "Attributes": [
                {
                    "Name": "Název",
                    "Description": "Název statusu",
                    "Type": "string",
                    "Required": true
                },
                {
                    "Name": "Popis",
                    "Description": "Popis statusu",
                    "Type": "text"
                }
            ]
        },
        {
            "Name": "Měny",
            "Description": "Tento dataset obsahuje jednotlivé měny.",
            "Attributes": [
                {
                    "Name": "Název",
                    "Description": "Název měny",
                    "Type": "string",
                    "Required": true
                }
            ]
        },
        {
            "Name": "Pozice",
            "Description": "Tento dataset obsahuje pozice v rámci firmy společně s popisem povinností pro danou pozici.",
            "Attributes": [
                {
                    "Name": "Název",
                    "Description": "Název pozice",
                    "Type": "string",
                    "Required": true
                },
                {
                    "Name": "Povinnosti",
                    "Description": "Popis povinností v rámci pozice",
                    "Type": "text"
                }
            ]
        }
    ]
}

=== sapoi/MetaRMS/SharedLibrary/Files/ApplicationDescriptorExamples/todo_list.json
{
    "ApplicationName": "My ToDo list",
    "LoginApplicationName": "todo_list",
    "DefaultLanguage": "en",
    "SystemDatasets": {
        "UsersDatasetDescriptor": {
            "Name": "Users",
            "PasswordAttribute": {
                "Name": "Password",
                "Type": "password",
                "Required": true
            },
            "Attributes": [
                {
                    "Name": "Username",
                    "Description": "Login username",
                    "Type": "username",
                    "Required": true,
                    "Unique": true
                }
            ]
        }
    },
    "Datasets": [
        {
            "Name": "ToDo list",
            "Description": "",
            "Attributes": [
                {
                    "Name": "Name",
                    "Description": "",
                    "Type": "string",
                    "Required": true
                },
                {
                    "Name": "Deadline",
                    "Description": "",
                    "Type": "datetime"
                },
                {
                    "Name": "Status",
                    "Description": "",
                    "Type": "Statuses",
                    "OnDeleteAction": "protect"
                },
                {
                    "Name": "Description",
                    "Type": "text"
                },
                {
                    "Name": "Related tasks",
                    "Description": "",
                    "Type": "ToDo list",
                    "OnDeleteAction": "setEmpty"
                },
                {
                    "Name": "Owner",
                    "Description": "",
                    "Type": "Users",
                    "OnDeleteAction": "cascade"
                }
            ]
        },
        {
            "Name": "Statuses",
            "Attributes": [
                {
                    "Name": "Name",
                    "Type": "string",
                    "Required": true
                }
            ]
        }
    ]
}

=== sapoi/MetaRMS/SharedLibrary/Files/ApplicationDescriptorExamples/sports_tracker.json
{
    "ApplicationName": "My sports tracker",
    "LoginApplicationName": "sports_tracker",
    "DefaultLanguage": "en",
    "SystemDatasets": {
        "UsersDatasetDescriptor": {
            "Name": "Users",
            "PasswordAttribute": {
                "Name": "Password",
                "Type": "password",
                "Required": true
            },
            "Attributes": [
                {
                    "Name": "Username",
                    "Description": "Login username",
                    "Type": "username",
                    "Required": true,
                    "Unique": true
                },
                {
                    "Name": "Info",
                    "Description": "Height, weight, etc.",
                    "Type": "text"
                }
            ]
        }
    },
    "Datasets": [
        {
            "Name": "Activities done",
            "Description": "This dataset contains done activities.",
            "Attributes": [
                {
                    "Name": "Sport",
                    "Type": "Sports",
                    "Required": true,
                    "Min": 1,
                    "Max": 1,
                    "OnDeleteAction": "protect"
                },
                {
                    "Name": "Duration in minutes",
                    "Type": "float",
                    "Required": true
                },
                {
                    "Name": "Date and time",
                    "Type": "datetime",
                    "Required": true
                },
                {
                    "Name": "Description",
                    "Type": "text"
                },
                {
                    "Name": "Feelings",
                    "Type": "text"
                },
                {
                    "Name": "Performance rate in %",
                    "Description": "0% = üòü, 50% = üòê, 100% = üôÇ",
                    "Type": "float",
                    "Min": 0,
                    "Max": 100
                }
            ]
        },
        {
            "Name": "Food intake",
            "Attributes": [
                {
                    "Name": "Name of the food",
                    "Type": "string",
                    "Required": true
                },
                {
                    "Name": "Recipe",
                    "Type": "Recipes",
                    "OnDeleteAction": "setEmpty"
                },
                {
                    "Name": "Description",
                    "Type": "text"
                },
                {
                    "Name": "Feelings",
                    "Type": "text"
                },
                {
                    "Name": "Rating in %",
                    "Description": "0% = üòü, 50% = üòê, 100% = üôÇ",
                    "Type": "float",
                    "Min": 0,
                    "Max": 100
                }
            ]
        },
        {
            "Name": "Sports",
            "Attributes": [
                {
                    "Name": "Name",
                    "Type": "string",
                    "Required": true
                },
                {
                    "Name": "Description",
                    "Type": "text"
                }
            ]
        },
        {
            "Name": "Recipes",
            "Attributes": [
                {
                    "Name": "Name",
                    "Type": "string",
                    "Required": true
                },
                {
                    "Name": "Description",
                    "Type": "text"
                }
            ]
        }
    ]
}

=== sapoi/MetaRMS/SharedLibrary/Files/DescriptorExamples/all_ref_test.json
{ 
  "LoginApplicationName":"all_ref_test",
  "ApplicationName":"all references test",
  "DefaultLanguage":"en",
  "SystemDatasets":
  {
    "UsersDatasetDescriptor":
    {
      "Name":"Uživatelé",
      "Description":"Dataset s uživateli aplikace.",
      "PasswordAttribute":
      {
        "Name":"Password",
        "Type":"password",
        "Safer":false
      },
      "Attributes":
      [
        {
          "Name":"Uživatelské jméno",
          "Type":"username"
        },
        {
          "Name":"Pozice",
          "Type":"Pozice"
        },
        {
          "Name":"Uživatel",
          "Type":"Uživatelé"
        }
      ]
    }
  },
  "Datasets": 
  [
    {
      "Name":"Pozice",
      "Attributes": 
      [
        {
          "Name":"Název pozice",
          "Type":"string"
        }
      ]
    },
    {
      "Name":"Měsíce",
      "Attributes": 
      [
        {
          "Name":"Jméno měsíce",
          "Type":"string"
        }
      ]
    },
    {
      "Name":"Narozeniny",
      "Attributes": 
      [
        {
          "Name":"Měsíc",
          "Type":"Měsíce"
        },
        {
          "Name":"Uživatelé",
          "Type":"Uživatelé"
        }
      ]
    }
  ]
}
